title: Just another bayesian enthusiast
author:
  name: Stippe
  email: smaurizio87@protonmail
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/SteffPy" }
