title: Data Perspectives
author:
  name: Data-perspectives
  email: dataperspectivesblog@gmail.com
url: thestippe.github.io
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: classic
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/SteffPy" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/11065831/stefano" }
    - { platform: github, user_url: "https://github.com/thestippe/" }
    - { platform: mastodon, user_url: "https://vis.social/@thestippe" }
      # - { platform: telegram, user_url "https://t.me/StefanoM87" }
  header_pages:
    - about
    - links
permalink: :title/
collections:
  category:
    output: true
gems: [jekyll-mermaid, jekyll-paginate]
show_excerpts: false
paginate: false
masthead: /docs/assets/images/logo_dp.png
sass:
  style: compressed
